[project]
name = "datapacks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beet>=0.110.0",
    "bolt>=0.49.1",
    "bolt-expressions>=0.18.0",
    "mcbookshelf>=3.0.1",
    "nbtlib>=1.12.1",
]
